<ips:template parameters="$release, $roms, $gameMedia, $flavors, $action, $registerUrl"/>

<div class="ipsPad" data-controller="vpdb.front.download.release" data-register="{$registerUrl}">
	<div class="ipsPageHeader ipsClearfix ipsSpacer_bottom">
		<h2 class="ipsType_sectionHead"><b>$release->name</b> of</h2>
		<br>
		<h1 class="ipsType_pageTitle"><b>{$release->game->title}</b></h1>
		<h2 class="ipsType_sectionHead">&nbsp;by {{foreach $release->authors as $i => $author}}{{if ($i > 0 && $i < count($release->authors) - 1)}}, {{endif}}
			{{if ($i > 0 && $i == count($release->authors) - 1)}} and {{endif}}
			{{if ($author->user->provider_id)}}{$author->user->member->link()|raw}{{else}}{$author->user->name}{{endif}}{{endforeach}}
		</h2>
	</div>

	<form id="releaseDownloadForm" class="ipsForm" method="post" action="{$action}">
		<!-- hidden variables -->
		<input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}" />
		{{foreach $gameMedia as $medium}}
		<input type="hidden" name="media[]" value="{$medium}" />
		{{endforeach}}

		<!-- table files --->
		<div class="ipsGrid ipsGrid_collapsePhone">
			{{foreach $release->versions as $i => $version}}
				{{foreach $version->files as $j => $versionFile}}
					{{if (preg_match("/^application\/x-visual-pinball-table/i", $versionFile->file->mime_type))}}
						<div class="ipsBox ipsGrid_span6 ipsSpacer_bottom">
							<div class="ipsColumns">

								<!-- thumb -->
								<div class="ipsColumn ipsColumn_narrow">
									<div class="ipsPad_half">
										<img src="{$versionFile->playfield_image->variations->square->url}" style="max-width: 100%"/>
									</div>
								</div>
								<div class="ipsColumn ipsColumn_fluid ipsTruncate ipsTruncate_line">
									<ul class="ipsFieldRow_content ipsField_fieldList">
										<li>

											<!-- checkbox -->
											<span class="ipsCustomInput">
												<input type="checkbox" name="tableFile[]" value="{$versionFile->file->id}" id="file{$versionFile->file->id}" {{if $i == 0 && $j == 0}}checked{{endif}}>
												<span></span>
											</span>

											<!-- filename -->
											<div class="ipsField_fieldList_content">
												<label for="file{$versionFile->file->id}" title="{$versionFile->file->name}" data-ipsTooltip>{$versionFile->file->name}</label>
											</div>

											<!-- version -->
											<div class="ipsFieldRow_desc">Version {$version->version}, released {expression="\IPS\DateTime::ts(strtotime($versionFile->released_at))->html()" raw="true"}</div>
											{{if $versionFile->flavor->orientation == "any" && $versionFile->flavor->lighting == "any"}}
												<p>{lang="vpdb_download_flavor_both_universal"}</p>
											{{else}}
												<p>{lang="vpdb_download_flavor_each" htmlsprintf="$flavors['orientation']['values'][$versionFile->flavor->orientation]['name'], $flavors['lighting']['values'][$versionFile->flavor->lighting]['name']"}</p>
											{{endif}}
										</li>
									</ul>
								</div>
							</div>
						</div>
					{{endif}}
				{{endforeach}}
			{{endforeach}}
		</div>

		<!-- media options -->
		<div class="ipsFieldRow ipsSpacer_top">
			<h3>{lang="vpdb_download_media"}</h3>
			<ul class="ipsFieldRow_content ipsList_reset">
				<li class="ipsFieldRow_inlineCheckbox">
					<span class="ipsCustomInput">
						<input type="checkbox" name="includeGameMedia" value="true" id="includeGameMedia">
						<span></span>
					</span>
					<label for="includeGameMedia">{lang="vpdb_download_include_game_media"}</label>
				</li>
				<li class="ipsFieldRow_inlineCheckbox">
					<span class="ipsCustomInput">
						<input type="checkbox" name="includePlayfieldImage" value="true" id="includePlayfieldImage">
						<span></span>
					</span>
					<label for="includePlayfieldImage">{lang="vpdb_download_include_playfield_image"}</label>
				</li>
				<li class="ipsFieldRow_inlineCheckbox">
					<span class="ipsCustomInput">
						<input type="checkbox" name="includePlayfieldVideo" value="true" id="includePlayfieldVideo">
						<span></span>
					</span>
					<label for="includePlayfieldVideo">{lang="vpdb_download_include_playfield_video"}</label>
				</li>
			</ul>
		</div>

		<!-- roms -->
		<div class="ipsFieldRow ipsSpacer_top ipsSpacer_double">
			<h3>{lang="vpdb_download_roms"}</h3>
			{{if count($roms) > 0}}
				<table class="ipsTable ipsTable_zebra vpdbTable">
					<thead>
						<tr>
							<th colspan="2"></th>
							<th>Version</th>
							<th>Language</th>
							<th>Notes</th>
							<th>DLs</th>
							<th>Size</th>
						</tr>
					</thead>
					<tbody>
						{{foreach $roms as $rom}}
						<tr>
							<td>
								<span class="ipsCustomInput">
									<input type="checkbox" name="rom[]" value="{$rom->id}" id="rom{$rom->id}">
									<span></span>
								</span>

							</td>
							<td>
								<div class="ipsField_fieldList_content">
									<label for="rom{$rom->id}">{$rom->file->name}</label>
								</div>
							</td>
							<td>{$rom->version}</td>
							<td>{{foreach $rom->languages as $lang}}<span>{$lang}</span> {{endforeach}}</td>
							<td>{$rom->notes}</td>
							<td>{$rom->file->counter->downloads}</td>
							<td>{filesize="$rom->file->bytes"}</td>

						</tr>
						{{endforeach}}
					</tbody>
				</table>
			{{else}}
				{lang="vpdb_download_no_roms_available"}
			{{endif}}
		</div>

		<!-- error message -->
		<div id="releaseDownloadError" class="ipsMessage ipsMessage_error" style="display:none">
		</div>

		<!-- buttons -->
		<div class="ipsType_center">
			<span>
				<button type="button" data-action="dialogClose" class="ipsButton ipsButton_large ipsButton_light">Cancel</button>
				<button type="button" data-action="download" class="ipsSpacer_left ipsSpacer_half ipsButton ipsButton_large ipsButton_important">Download</button>
			</span>
		</div>
		<div class="ipsClearfix"></div>
	</form>
</div>
