<ips:template parameters="$table, $headers, $releases" />
{{if count( $releases )}}
	{{foreach $releases as $release}}
	<li class='ipsDataItem'>
		<div class='ipsDataItem_generic ipsDataItem_size3 ipsPos_top'>
			<a href='{$release->url}' class='ipsType_blendLinks'>
				{template="thumbImage" group="global" app="core" params="$release->thumb->image->url, $release->id"}
			</a>
		</div>
		<div class='ipsDataItem_main'>

			<!-- game title -->
			<h4 class='ipsDataItem_title ipsType_sectionHead ipsContained_container'>
				<span class='ipsType_break ipsContained'><a href='{$release->url}'>{$release->game->title} ({$release->game->manufacturer} {$release->game->year})</a></span>
			</h4>

			<!-- release name -->
			<p class='ipsDataItem_meta'>
				{$release->name} v{$release->versions[0]->version}
			</p>

			<!-- authors -->
			<p class='ipsType_reset ipsType_light ipsType_blendLinks'>
				By {{foreach $release->authors as $i => $author}}{{if ($i > 0 && $i < count($release->authors) - 1)}}, {{endif}}
					{{if ($i > 0 && $i == count($release->authors) - 1)}} and {{endif}}
					{{if ($author->user->provider_id)}}{$author->user->member->link()|raw}{{else}}{$author->user->name}{{endif}}{{endforeach}}
			</p>

			<!-- downloads -->
			<!-- footer -->
			<ul class='ipsList_inline ipsSpacer_top'>
				<li class='ipsType_light ipsType_medium'>
					<i class='fa fa-clock-o'></i> {datetime="strtotime($release->created_at)"}</a>
				</li>
				{{if $release->item->comments > -1}}
					<li class='ipsType_light ipsType_medium'>
						<i class='fa fa-comment'></i> {lang="num_comments" pluralize="$release->item->comments"}
					</li>
				{{endif}}
				{{if $release->counter->downloads > -1}}
					<li class='ipsType_light ipsType_medium'>
						<i class='fa fa-arrow-circle-down'></i> {lang="num_downloads" pluralize="$release->counter->downloads"}
					</li>
				{{endif}}
				{{if settings.reputation_enabled && count($release->item->templateReactions())}}
					<li>{template="searchReaction" group="search" app="core" params="$release->item->templateReactions(), $release->url->setQueryString('do', 'showReactions'), $release->item->reactionCount()"}</li>
				{{endif}}
			</ul>
		</div>
	</li>
	{{endforeach}}
{{endif}}