<ips:template parameters="$release, $otherAuthors, $condensed" />
{{if $condensed}}
	<span class='ipsThumb_bg ipsThumb_small ipsPos_left' style='background-image: url("{file="$release->thumb->image->url"}")'>
		<img src='{file="$release->thumb->image->url"}' alt='{lang="idm_screenshot_for" sprintf="$release->name"}' class="">
	</span>
{{else}}
	<div class='ipsColumns ipsColumns_collapsePhone'>
		<div class='ipsColumn ipsColumn_medium'>
			<a href='{$release->url}'>
				<img src='{file="$release->thumb->image->url"}' class='ipsImage ipsStream_image' alt='{lang="idm_screenshot_for" sprintf="$release->name"}'>
			</a>
		</div>
		<div class='ipsColumn ipsColumn_fluid ipsStream_snippetInfo'>
			<p class='ipsType_reset ipsType_light ipsType_normal'>{lang="version"} {$release->versions[0]->version}</p>
			<p class='ipsType_reset ipsType_normal'><i class='fa fa-download'></i> {lang="num_downloads" pluralize="$release->counter->downloads"}</p>
			<div class='ipsType_richText ipsType_break ipsType_medium'
				{{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}
					data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='3 lines' data-ipsTruncate-watch='false'
				{{else}}
					data-searchable data-findTerm
				{{endif}}>
				{$release->description|raw}
			</div>
			{{if count($otherAuthors)}}
				<h4>Co-Authors</h4>
				{{foreach $otherAuthors as $author}}
					{{if ($author->user->member)}}
						{template="userPhoto" group="global" app="core" params="$author->user->member, ($view !== 'condensed') ? 'mini' : 'tiny'"}
					{{else}}
					<span class="ipsUserPhoto ipsUserPhoto_{{if ($view !== 'condensed')}}mini{{else}}tiny{{endif}}">
						<img src="//www.gravatar.com/avatar/{$author->user->gravatar_id}?default=retro" alt="{$author->user->name}" title="{$author->user->name}">
					</span>
			{{endif}}
				{{endforeach}}
			{{endif}}
		</div>
	</div>
{{endif}}