<ips:template parameters="$release, $flavorGrid, $comments, $isLogged"/>

<div class="ipsPad">

	<!-- title -->
	<div class="ipsPageHeader ipsClearfix ipsSpacer_bottom">
		<h1 class="ipsType_pageTitle">{$release->game->title}</h1>
		<h2 class="ipsType_sectionHead">&nbsp;({$release->game->manufacturer} {$release->game->year})</h2>
		<h2>{$release->name} <span class="ipsType_unbold">by</span></h2>
	</div>
	<div class="ipsBox">
		<div class="ipsColumns ipsColumns_collapsePhone">

			<!-- left column -->
			<article class="ipsColumn ipsColumn_fluid">
				<div class="ipsPad">

					<!-- authors -->
					<div class="ipsClearfix"></div>
					{{foreach $release->authors as $author}}
						<div class="ipsPhotoPanel ipsPhotoPanel_tiny ipsSpacer_bottom ipsPos_left" style="margin-right:15px">
							{{if ($author->user->provider_id)}}
								{template="userPhoto" app="core" group="global" params="$author->user->member, 'tiny'"}
								<div>
									<p class='ipsType_reset ipsType_normal ipsType_blendLinks'>{$author->user->member->link()|raw}</p>
								</div>
							{{else}}
								<span class="ipsUserPhoto ipsUserPhoto_tiny">
									<img src="//www.gravatar.com/avatar/{$author->user->gravatar_id}?default=retro">
								</span>
								<div>
									<p class="ipsType_reset ipsType_normal ipsType_blendLinks">{$author->user->name}</p>
								</div>
							{{endif}}
							<div class="ipsType_light">
								{{foreach $author->roles as $role}}
								{$role}
								{{endforeach}}
							</div>
						</div>
					{{endforeach}}

					<!-- reputation -->
					{template="reputation" app="core" group="global" params="$release->item"}
					<div class="ipsClearfix"></div>

					<!-- stats (date, num downloads/views) -->
					<ul class='ipsList_inline'>
						<li class='ipsType_light ipsType_medium'>
							<i class='fa fa-clock-o'></i> {datetime="strtotime($release->created_at)"}</a>
						</li>
						<li class='ipsType_light ipsType_medium'>
							<i class='fa fa-arrow-circle-down'></i> {lang="num_downloads" pluralize="$release->counter->downloads"}
						</li>
						<li class='ipsType_light ipsType_medium'>
							<i class='fa fa-eye'></i> {lang="num_views_with_number" pluralize="$release->counter->views"}
						</li>
					</ul>

					<hr class="ipsHr">

					<!-- description -->
					<section class='ipsType_normal ipsSpacer_top'>
						<div class='ipsType_richText ipsContained ipsType_break' itemprop='text' data-controller='core.front.core.lightboxedImages'>
							{$release->description|raw}
						</div>
					</section>

					<!-- acknowledgements -->
					{{if $release->acknowledgements}}
						<section class='ipsType_normal ipsSpacer_top'>
							<h2>{lang="vpdb_release_acknowledgements"}</h2>
							<div class='ipsType_richText ipsContained ipsType_break' itemprop='text' data-controller='core.front.core.lightboxedImages'>
								{$release->acknowledgements|raw}
							</div>
						</section>
					{{endif}}

					<!-- mod permissions -->
					<section class='ipsType_normal ipsSpacer_top'>
						<h2>{lang="vpdb_release_mod_permissions"}</h2>
						{{if $release->license === 'by-sa'}}
							<p>{lang="vpdb_release_mod_permission_by_sa" sprintf="count($release->authors) == 1 ? '' : 's'"}</p>
						{{else}}
							<p>{lang="vpdb_release_mod_permission_by_nd" sprintf="count($release->authors) == 1 ? '' : 's'"}</p>
						{{endif}}
					</section>

					<!-- flavor grid -->
					<section class='ipsType_normal ipsSpacer_top'>
						<h2>{lang="vpdb_release_flavors"}</h2>
						<table class="ipsTable vpdbTable">
							<thead>
							<tr>
								<th width="55"></th>
								<th>Orientation</th>
								<th>Lighting</th>
								<th>Compatibility</th>
								<th>Size</th>
							</tr>
							</thead>
							<tbody>
							{{foreach $flavorGrid as $flavor}}
								<tr>
									<td>
										<a href="{$flavor['file']->playfield_image->variations->full->url}" data-ipsLightbox>
											<img src="{$flavor['file']->playfield_image->variations->square->url}" width="40" height="40">
										</a>
									</td>
									<td>{$flavor['orientation']['name']}<br><i>{$flavor['orientation']['other']}</i></td>
									<td>{$flavor['lighting']['name']}<br><i>{$flavor['lighting']['other']}</i></td>
									<td>
										{{foreach $flavor['file']->compatibility as $index => $compat}}
											{{if $index > 0}}, {{endif}}{$compat->label}
										{{endforeach}}
									</td>
									<td>{filesize="$flavor['file']->file->bytes"}</td>
								</tr>
							{{endforeach}}
							</tbody>
						</table>
					</section>

				</div>

			</article>

			<!-- right column -->
			<aside class="ipsColumn ipsColumn_wide ipsAreaBackground">
				<div class="ipsPad">

					<!-- logo -->
					{{if $release->game->logo}}
					<img src="{$release->game->logo->variations->medium->url}" alt="{$release->game->title}" class="ipsSpacer_bottom"
						 style="max-width:100%">
					{{endif}}

					<!-- playfield image -->
					<div class="ipsAreaBackground_reset ipsPad_half">
						<a href="{$release->versions[0]->files[0]->playfield_image->variations->full->url}" data-ipsLightbox>
							<img src="{$release->thumb->image->url}" alt="{$release->title}" style="max-width:100%">
						</a>
					</div>

					<!-- download button -->
					<ul class="ipsToolList ipsToolList_vertical ipsSpacer_top ipsClearfix">
						<li>
							{{if $isLogged}}
								<a href="{$release->download}" data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-title='{lang="download"}' class="ipsButton ipsButton_fullWidth ipsButton_large ipsButton_important">Download</a>
							{{else}}
								{template="downloadTeaser" app="vpdb" group="releases"}
							{{endif}}

						</li>
					</ul>
				</div>
			</aside>
		</div>
	</div>

	<!-- comments -->
	<div data-role='releaseComments'>
		{{if $comments}}
		<br>
		<a id="replies"></a>
		<h2 class='ipsHide'>{lang="user_feedback"}</h2>
		{$comments|raw}
		{{endif}}
	</div>
</div>