<ips:template parameters="$release, $game"/>

<!-- title -->
<div class="ipsPageHeader ipsClearfix ipsSpacer_bottom">
	<h1 class="ipsType_pageTitle">{$release->game->title}</h1>
	<h2 class="ipsType_sectionHead">&nbsp;({$release->game->manufacturer} {$release->game->year})</h2>
	<h2>{$release->name}</h2>
</div>
<div class="ipsBox">
	<div class="ipsColumns ipsColumns_collapsePhone">

		<!-- left column -->
		<article class="ipsColumn ipsColumn_fluid">
			<div class="ipsPad">

				<!-- description -->
				{$release->descriptionParsed|raw}

				<!-- authors -->
				<h2>Authors</h2>
				{{foreach $release->authors as $author}}
					{{if ($author->user->provider_id)}}
						<div class='ipsPhotoPanel ipsPhotoPanel_tiny ipsClearfix ipsSpacer_bottom'>
							{template="userPhoto" app="core" group="global" params="$author->user->member, 'tiny'"}
							<div>
								<p class='ipsType_reset ipsType_normal ipsType_blendLinks'>
									{$author->user->member->link()|raw}
								</p>
								<div class="ipsType_light">
									{{foreach $author->roles as $role}}
										{$role}
									{{endforeach}}
								</div>
							</div>
						</div>
					{{else}}
						<div class="ipsPhotoPanel ipsPhotoPanel_tiny ipsClearfix ipsSpacer_bottom">
							<span class="ipsUserPhoto ipsUserPhoto_tiny">
								<img src="//www.gravatar.com/avatar/{$author->user->gravatar_id}?default=retro">
							</span>
							<div>
								<p class="ipsType_reset ipsType_normal ipsType_blendLinks">
									{$author->user->name}
								</p>
								<div class="ipsType_light">
									{{foreach $author->roles as $role}}
									{$role}
									{{endforeach}}
								</div>
							</div>
						</div>
					{{endif}}
				{{endforeach}}

			</div>
		</article>

		<!-- right column -->
		<aside class="ipsColumn ipsColumn_wide ipsAreaBackground">
			<div class="ipsPad">
				{{if $game->logo}}
				<img src="{$game->logo->variations->medium->url}" alt="{$game->title}" class="ipsSpacer_bottom"
					 style="max-width:100%">
				{{endif}}
				<div class="ipsAreaBackground_reset ipsPad_half">
				<span href="{$release->thumb->image->url}" data-ipsLightbox
					  data-ipsLightbox-group="release_{$release->id}"
					  data-fullURL="{$release->thumb->image->url}">
					<img src="{$release->thumb->image->url}" alt="{$release->title}" style="max-width:100%">
				</span>
				</div>
			</div>
		</aside>
	</div>
</div>