<ips:template parameters="$back, $continue"/>

<div class='ipsGrid ipsGrid_collapsePhone'>
	<div class='ipsGrid_span3'></div>
	<div class='ipsGrid_span6'>
		<p>Just one second...</p>
		<h1>{setting="board_name"} <i class="fa fa-heart"></i> VPDB!</h1>
		<p>The content you just visited came from VPDB, an open and centralized database for virtual pinball and a joint
			venture with {setting="board_name"}.</p>
		<p>If you continue, we will create an account for you at VPDB that allows you to download and rate content here
			through VPDB. If you already have an account at VPDB, just make sure you used the same email address as here and
			your existing account will be updated.</p>
		<div class="ipsPos_right">
			<a href="" class="ipsButton ipsButton_light">No, thanks</a>
			<a href="" class="ipsButton ipsButton_important">Continue</a>
		</div>
	</div>
	<div class='ipsGrid_span3'></div>
</div>


