<ips:template parameters="$registerUrl"/>

<div class="ipsPad" data-controller="vpdb.front.register" data-register="{$registerUrl}">
	<p>Just one second...</p>
	<h1>{setting="board_name"} <i class="fa fa-heart"></i> VPDB!</h1>
	<p>The content you just visited came from VPDB, an open and centralized database for virtual pinball and a joint
		venture with {setting="board_name"}.</p>
	<p>If you continue, we will create an account for you at VPDB that allows you to download and rate content here
		through VPDB. If you already have an account at VPDB, just make sure you used the same email address as here and
		your existing account will be updated.</p>

	<!-- buttons -->
	<div class="ipsType_center">
			<span>
				<button type="button" data-action="dialogClose" class="ipsButton ipsButton_large ipsButton_light">No, thanks</button>
				<button type="button" data-action="register" class="ipsSpacer_left ipsSpacer_half ipsButton ipsButton_large ipsButton_important">Continue</button>
			</span>
	</div>
	<div class="ipsClearfix"></div>
</div>