<ips:template parameters="$registerUrl, $vpdbUrl"/>

<div class="ipsPad" data-controller="vpdb.front.register" data-register="{$registerUrl}">
	<p>Just one second...</p>
	<h1>{setting="board_name"} <i class="fa fa-heart"></i> VPDB!</h1>
	<p>The content you just visited came from VPDB, an open and centralized database for virtual pinball and a joint
		venture with {setting="board_name"}.</p>
	<p>If you continue, we will create an account for you at VPDB that allows you to download and rate content here
		through VPDB. If you already have an account under the same email as here, that account will be used.</p>

	<p>If your account at VPDB has a different email, you can link your account under <i>Linked Accounts</i>
		<a href="{$vpdbUrl}/profile/settings" target="_blank">here</a>.</p>

	<!-- error message -->
	<div id="registerError" class="ipsMessage ipsMessage_error" style="display:none"></div>

	<!-- buttons -->
	<div class="ipsType_center">
			<span>
				<button type="button" data-action="dialogClose" class="ipsButton ipsButton_large ipsButton_light">No, thanks</button>
				<button type="button" data-action="register" class="ipsSpacer_left ipsSpacer_half ipsButton ipsButton_large ipsButton_important">Continue</button>
			</span>
	</div>
	<div class="ipsClearfix"></div>
</div>